require("hs.ipc")

hs.loadSpoon("MouseFollowsFocus")

hs.hotkey.bind({"ctrl", "shift"}, "up", function()
    hs.window.filter.focusNorth()
    spoon.MouseFollowsFocus:updateMouse(hs.window.focusedWindow())
end)
hs.hotkey.bind({"ctrl", "shift"}, "left", function()
    hs.window.filter.focusWest()
    spoon.MouseFollowsFocus:updateMouse(hs.window.focusedWindow())
end)
hs.hotkey.bind({"ctrl", "shift"}, "down", function()
    hs.window.filter.focusSouth()
    spoon.MouseFollowsFocus:updateMouse(hs.window.focusedWindow())
end)
hs.hotkey.bind({"ctrl", "shift"}, "right", function()
    hs.window.filter.focusEast()
    spoon.MouseFollowsFocus:updateMouse(hs.window.focusedWindow())
end)
